CREATE TABLE PRODUCTS(
    Id Serial,
    PRODUCT_NAME varchar(100) NOT NULL,
    PRODUCT_DESCRIPTION varchar(100) NOT NULL,
    PRODUCT_CATEGORY varchar(100) NOT NULL,
    PRODUCT_PRICE INT NOT NULL
);